

SCHEDULE_DIR_PATH = "data\schedule"
CATEGORY_DIR_PATH = "data\category"
ORIGINAL_HOST_FILE_PATH = "data\original"
STATUS_FILE_PATH = "data\__status__"
HOST_FILE_PATH = "c:\Windows\System32\Drivers\etc\hosts"
INIT_FILE = "__init__"
LOCALHOST_1 = "127.0.0.1"
LOCALHOST_2 = "0.0.0.0"

ALREADY_EXSISTS = "ALREADY_EXSISTS"
SUCCESS = "SUCCESS"
DOES_NOT_EXSIST = "DOES_NOT_EXSIST"
CHANGE = "CHANGE"
STOPED = "STOPED"
BLOCKING = "BLOCKING"
DISABLED = "DISABLED"
STARTING = "START"
ENDING = "END"
LOAD_ALL = "load all"

SCHEDULE_TIME_FORMAT = "%H:%M:%S"
IP_ADDRESS_REGULAR_EXPRESSION = r"(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})"
