SCHEDULE_DIR_PATH = "data\schedule"
CATEGORY_DIR_PATH = "data\category"
ORIGINAL_HOST_FILE_PATH = "data\original"
STATUS_FILE_PATH = "data\__status__"
# HOST_FILE_PATH = "c:\Windows\System32\Drivers\etc\hosts"
HOST_FILE_PATH = "data\hosts"
LOCAL_HOST = "127.0.0.1"

ALREADY_EXSISTS = 'ALREADY_EXSISTS'
SUCCESS = 'SUCCESS'
DOES_NOT_EXSIST = 'DOES_NOT_EXSIST'
CHANGE = 'CHANGE'
STOPED = 'STOPED'
BLOCKING = "BLOCKING"
DISABLED = "DISABLED"
STARTING = 'START'
ENDING = 'END'
LOAD_ALL = 'load all'

SCHEDULE_TIME_FORMAT = "%H:%M:%S"
INIT_FILE = "__init__"